name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello GitHub Actions!
      - name: Print a few lines
        run: |
          echo Fisrt line!
          echo Second line!
          echo Third line!
